# Generated by Django 4.2.3 on 2023-08-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_branch', models.CharField(max_length=30)),
                ('s_addr', models.CharField(max_length=30)),
                ('s_batch', models.CharField(max_length=30)),
                ('s_email', models.CharField(max_length=30)),
            ],
        ),
    ]
